name: Construção do Artefato

on: 
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        go_version: ['1.22']
        os: ['ubuntu-latest']
    steps:
      - uses: actions/checkout@v4

      - name: Configuração do Go
        uses: actions/setup-go@v4
        with:
          go-version: ${{ matrix.go_version }}

      - name: Build
        run: go build -v main.go

      - name: Upload e Construção do Artefato
        uses: actions/upload-artifact@v4
        with:
          name: programa
          path: main

  docker:
    needs: build
    uses: ./.github/workflows/docker.yml
    secrets: inherit

  deploy:
    needs: build
    uses: ./.github/workflows/deploy_ec2.yml
    secrets: inherit

