name: Entrega Contínua EC2

on:
  push:
    branches: [ "main" ]

jobs:
  deploy_ec2:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v4
        with:
           go-version: '1.22'

      - name: Build
        run: go build main.go

      - name: SCP para EC2
        uses: appleboy/scp-action@v1
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SECRET_KEY }}
          source: "templates,assets,main"
          target: /home/${{ secrets.EC2_USERNAME }}

      - name: Reinicia Projeto Go
        uses: appleboy/ssh-action@master
        env:
          DB_HOST: ${{ secrets.RDS_HOST }}
          DB_USER: ${{ secrets.RDS_USER }}
          DB_NAME: ${{ secrets.RDS_DBNAME }}
          DB_PASSWORD: ${{ secrets.RDS_PASSWORD }}
          DB_PORT: ${{ secrets.RDS_PORT }}
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SECRET_KEY }}
          envs: DB_HOST,DB_USER,DB_NAME,DB_PASSWORD,DB_PORT
          script: |
            # Cria diretório se não existir
            sudo mkdir -p /etc/projeto

            # Adiciona as variáveis no arquivo
            sudo echo "DB_HOST=$DB_HOST" | tee /etc/projeto/db.env > /dev/null
            sudo echo "DB_USER=$DB_USER" | tee -a /etc/projeto/db.env > /dev/null
            sudo echo "DB_NAME=$DB_NAME" | tee -a /etc/projeto/db.env > /dev/null
            sudo echo "DB_PASSWORD=$DB_PASSWORD" | tee -a /etc/projeto/db.env > /dev/null
            sudo echo "DB_PORT=$DB_PORT" | tee -a /etc/projeto/db.env > /dev/null

            # Protege o arquivo
            sudo chmod 600 /etc/projeto/db.env

            # Reinicia o serviço
            sudo systemctl daemon-reload
            sudo systemctl restart projeto.service
