on:
  workflow_run:
    workflows: ["Lint"]
    types: [completed]
  
jobs:

  test:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

    - name: Build
      run: go build -v main.go

    - name: Upload main artifact
      uses: actions/upload-artifact@v4
      with:
        name: main
        path: ./

    - name: Start app
      run: go run main

    - name: Test
      run: go build -v main_test.go


